### PR TITLE
launch s0 instance w/o default VPC

### LINKED ISSUE #13: launch-s0-instance.sh should determine when default VPC is missing and take a VPC as an argument
It has been determined during the EAP that it is common practice to delete default VPC, which launch-s0-instance.sh relies on. As a result the script fails:

```
[ec2-user@ip-10-3-4-105 ~]$ bash -i ./launch-s0-instance.sh -s vchokshi@iot4.net -k vstack-vstack -b vstack-vstack-af3yhtlsob7q4yo2c3zd46m3fq --instance-profile elastio
Validating bucket "vstack-vstack-af3yhtlsob7q4yo2c3zd46m3fq"...
Validating KMS key alias "vstack-vstack"...
An error occurred (VPCIdNotSpecified) when calling the CreateSecurityGroup operation: No default VPC for this user
Failed to create a security group to open ports for s0 server and ssh. Do you have enough permissions?
With a manually created security group as a workaround it doesn't go further than this.
```

```
[ec2-user@ip-10-3-4-105 ~]$ bash -i ./launch-s0-instance.sh -s vchokshi@iot4.net -k vstack-vstack -b vstack-vstack-af3yhtlsob7q4yo2c3zd46m3fq --instance-profile elastio -g elastio
Validating bucket "vstack-vstack-af3yhtlsob7q4yo2c3zd46m3fq"...
Validating KMS key alias "vstack-vstack"...
Validating instance profile "elastio"...
Launching "ec2-user-s0-server" (instance type m5d.2xlarge) with the latest Elastio s0 AMI (ami-0a9a394b3140a1d65)
An error occurred (VPCIdNotSpecified) when calling the RunInstances operation: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC.
```

As a solution: when the script is launched it should validate if the default VPC is present, otherwise it should be able to take VPC as an argument. Besides, an error message along the lines of "Default VPC is missing, enter --vpc <VPC_ID> as an argument and relaunch the script"

### PR DESCRIPTION
**Pull request by e-kov**
The subnet ID is needed in this case. So it's added as an argument to
the script.

Resolves #13

### CODE REVIEW

File: scripts/launch-s0-instance.sh [hunk 1]
```diff
@@ -188,6 +188,9 @@ usage()
     echo "                              NOTE: The group existance and the open ports in the group aren't checked."
     echo "                                    The script may not have permissions and assumes that the group is configured properly."
     echo
+    echo "  -n | --subnet-id          : Optional. A subnet ID to use instead of the default subnet associated with the default VPC. Obligatory if you have no default VPC."
```
Comment (anelson) [inline scripts/launch-s0-instance.sh:191]:
```suggestion
    echo "  -n | --subnet-id          : Optional. A subnet ID to use instead of the default subnet associated with the default VPC."
```

**Review by anelson — CHANGES_REQUESTED** [review]

**Review by anelson — APPROVED** [review]
